FROM php:8.0-cli
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN apt-get update && apt-get install unzip tar git -y
RUN echo "phar.readonly=0" > /usr/local/etc/php/conf.d/phar.ini
RUN if [ -d vendor ]; then \
      rm -rf vendor; \
    fi \
    && composer install --no-dev --prefer-dist

CMD [ "./vendor/bin/drutiny" ]
