<?php

namespace Drutiny\PolicySource;

use Drutiny\LanguageManager;

/**
 * Provide policies for Drutiny to use.
 */
interface PolicySourceInterface
{

  /**
   * The short name that defines this source.
   */
    public function getName();

  /**
   * Return a list of policy definitions.
   *
   * Each definition should contain keys for name and description.
   * The definition is passed to the ::load() function to load a Policy object.
   *
   * @param \Drutiny\LanguageManager $languageManager
   */
    public function getList(LanguageManager $languageManager);

  /**
   * Load a Drutiny\Policy object.
   *
   * @param array $definition
   *  A definition array generated by PolicySourceInterface::getList().
   */
    public function load(array $definition);

  /**
   * Get the weight of the source.
   *
   * @return int a number to indicate which priority the policies should take
   *  if duplicates are provided by other sources.
   */
    public function getWeight();
}
